### ISSUE TITLE
[webui] remove Todo text on Search page

### ISSUE THREAD

**Issue by mrvivacious** [mrvivacious/My_Bhagavad_Gita#22]
**Story description**
1. go to https://mrvivacious.github.io/My_Bhagavad_Gita/
2. click on Search
3. note how it says "Todo"

**Acceptance criteria:**
Pull request is created. In that request, the todo text is removed (so, i only want to see `Search by phrase`)

Work description:
[This is the line of code that needs to be edited](https://github.com/mrvivacious/My_Bhagavad_Gita/blob/11289addf85080d3fb62ee92690fa23588fe3e0d/index.html#L123)

**Comment by bharath090909** [comment]
@mrvivacious  Can i take up on this issue?

**Comment by mrvivacious** [comment]
:0 sure 🙂 thank u

**Comment by bharath090909** [comment]
@mrvivacious I have completed the task and raised PR. Please check and let me know if any changes. Thank you for the opportunity.

**Comment by mrvivacious** [comment]
Everything looks good! Thank you 🎆 I'm glad you found the issue and picked this up :)))


If you had a chance to use the tool, let me know if there's anything broken or if you have any ideas. Or, just make an issue or PR 😉

**Comment by mrvivacious** [comment]
Resolved with commit 7bfd8fc4cef3a6f06664aea80dfc7c9c37deebde
