### ISSUE TITLE
[webUI] audio should appear on hover in search results

### ISSUE THREAD

**Issue by mrvivacious** [mrvivacious/My_Bhagavad_Gita#30]
**Story description**
1. go to https://mrvivacious.github.io/My_Bhagavad_Gita/
2. click search button
3. note that search feature appears on page
4. type "duty"
5. note that results page populates with different verses

**acceptance criteria**
Each result should have an audio play icon under the verse
when the user hovers the mouse over that icon, the icon becomes an <audio> with that verse.
when the user hovers off the audio tag, it returns to icon mode

**Why?**
The browser complains when "too many" audio tags are added to a page, to my surprise. However, I still want the user to listen to verses in the Search area.
The above method allows the user to see that the verse offer an option to listen to them WITHOUT dynamically creating so many audio tags that the browser throws an error and adds none of the audio tags to the page.

**resources**
[constructAudioURL function](https://github.com/mrvivacious/My_Bhagavad_Gita/blob/7c784d695fa33d41b0e718fa2e70d2a6fc53426b/gui/website.js#L23)

Can handle the addition of the icon with an event listener in this [function](https://github.com/mrvivacious/My_Bhagavad_Gita/blob/7c784d695fa33d41b0e718fa2e70d2a6fc53426b/gui/searchFeature.js#L48). Or, if there's a better method, then whoever picks this issue up can propose that.

**Comment by ronisarkarexe** [comment]
@mrvivacious can you assign me

**Comment by mrvivacious** [comment]
Assigned u ✔️ thanks!!!!

**Comment by mrvivacious** [comment]
Here's a [link](https://www.flaticon.com/free-icon/play-button_375) to an icon I found, simple "play" icon. Feel free to use another icon that's similar in meaning.

**Comment by mrvivacious** [comment]
thanks for trying to help everyone.
ended up doing it myself :)
